"""Add user_id, order_id, and payment_status to invoice

Revision ID: 75389edc8690
Revises: 7bc7347a1953
Create Date: 2025-11-13 17:22:03.576810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75389edc8690'
down_revision: Union[str, Sequence[str], None] = '7bc7347a1953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('invoices', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'CANCELLED', name='paymentstatus'), nullable=False))
    op.create_index(op.f('ix_invoices_order_id'), 'invoices', ['order_id'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'invoices', 'users', ['user_id'], ['id'])
    op.alter_column('stock_movements', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('warehouse_documents', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('warehouse_documents', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warehouse_documents', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('warehouse_documents', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stock_movements', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_order_id'), table_name='invoices')
    op.drop_column('invoices', 'payment_status')
    op.drop_column('invoices', 'order_id')
    #op.drop_column('invoices', 'user_id')
    # ### end Alembic commands ###
